// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSVBVqvTi854H5dhG1UhySMDi5LDugLIk',
    appId: '1:246956142166:web:8393665eb9b23a4090d5f7',
    messagingSenderId: '246956142166',
    projectId: 'gems-gemini-api-competition',
    authDomain: 'gems-gemini-api-competition.firebaseapp.com',
    storageBucket: 'gems-gemini-api-competition.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMJDsubnP01HQBLvEpg7AzKrf61uh2sI',
    appId: '1:246956142166:android:99d2e681909afffd90d5f7',
    messagingSenderId: '246956142166',
    projectId: 'gems-gemini-api-competition',
    storageBucket: 'gems-gemini-api-competition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_cKF1OtBSQTfRBqSeS9e2kmjGftD2ts',
    appId: '1:246956142166:ios:ae7009aa489d9a1b90d5f7',
    messagingSenderId: '246956142166',
    projectId: 'gems-gemini-api-competition',
    storageBucket: 'gems-gemini-api-competition.appspot.com',
    iosClientId: '246956142166-8468cf2ii49up0id6dcovujvblbrbp2r.apps.googleusercontent.com',
    iosBundleId: 'com.gem.diaryFlutter',
  );

}